name: RevPAR
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#204821'
    - '#ffffff'
    - '#d8af60'
    - '#000000'
    - '#829983'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
